Repository wookey-project/ewok-kernel, pull requests merged in 2019-06, with the labels that each got.

#4 [update] Modified syscalls mechanism
  src/Ada/ewok-softirq.adb
  src/Ada/ewok-softirq.ads
  src/Ada/ewok-syscalls-handler.adb
  src/Ada/ewok-syscalls.ads
  src/Ada/ewok-tasks.adb
  src/Ada/ewok.ads
  src/Ada/syscalls/ewok-syscalls-cfg-dev.adb
  src/Ada/syscalls/ewok-syscalls-cfg-dev.ads
  src/Ada/syscalls/ewok-syscalls-cfg-gpio.adb
  src/Ada/syscalls/ewok-syscalls-cfg-gpio.ads
  src/Ada/syscalls/ewok-syscalls-cfg.adb
  src/Ada/syscalls/ewok-syscalls-cfg.ads
  src/Ada/syscalls/ewok-syscalls-dma.adb
  src/Ada/syscalls/ewok-syscalls-dma.ads
  src/Ada/syscalls/ewok-syscalls-gettick.adb
  src/Ada/syscalls/ewok-syscalls-gettick.ads
  src/Ada/syscalls/ewok-syscalls-init.adb
  src/Ada/syscalls/ewok-syscalls-init.ads
  src/Ada/syscalls/ewok-syscalls-ipc.adb
  src/Ada/syscalls/ewok-syscalls-ipc.ads
  src/Ada/syscalls/ewok-syscalls-lock.adb
  src/Ada/syscalls/ewok-syscalls-lock.ads
  src/Ada/syscalls/ewok-syscalls-log.adb
  src/Ada/syscalls/ewok-syscalls-log.ads
  src/Ada/syscalls/ewok-syscalls-reset.adb
  src/Ada/syscalls/ewok-syscalls-reset.ads
  src/Ada/syscalls/ewok-syscalls-rng.adb
  src/Ada/syscalls/ewok-syscalls-rng.ads
  src/Ada/syscalls/ewok-syscalls-sleep.adb
  src/Ada/syscalls/ewok-syscalls-sleep.ads
  src/Ada/syscalls/ewok-syscalls-yield.adb
  src/Ada/syscalls/ewok-syscalls-yield.ads
  src/C/exported/syscalls.h
  src/C/usart.c
Labels: enhancement

#6 add missing new dir to prove.gpr file
  prove/prove.gpr
Labels: bug

#7 reducing pointers usage, allowing SPARK mode [WIP]
  Makefile
  src/Ada/ewok-dma_shared.ads
  src/Ada/ewok-ipc.adb
  src/Ada/ewok-ipc.ads
  src/Ada/ewok-sched.adb
  src/Ada/ewok-syscalls-handler.adb
  src/Ada/ewok-tasks.adb
  src/Ada/ewok-tasks.ads
  src/Ada/ewok.ads
  src/Ada/exported/ewok-exported-dma.ads
  src/Ada/syscalls/ewok-syscalls-ipc.adb
  src/arch/Ada/types-c.ads
  src/arch/socs/stm32f439/Ada/soc-dma-interfaces.ads
Labels: enhancement

#14 [enhancement] Removed unused code
  .gitignore
  Makefile
  src/Ada/ewok-init.adb
  src/Ada/libgnat/gnat/link_list.txt
  src/Makefile
  src/arch/Kconfig
  src/arch/cores/armv7-m/Ada/m4-fpu.ads
  src/arch/cores/armv7-m/C/m4-cpu.h
  src/arch/cores/armv7-m/Makefile.objs
  src/arch/libc.c
  src/arch/libc.h
  src/arch/stack_check.c
  src/arch/stack_check.h
Labels: cleaning

#16 [bugfix] Fixed some few errors in libgnat GPR build file
  src/Ada/libgnat/gnat.gpr
Labels: enhancement

#17 [enhancement] Removed unused code and added some few comments
  src/arch/cores/armv7-m/m4-systick.ads
  src/arch/socs/stm32f439/soc-dwt-interfaces.ads
  src/arch/socs/stm32f439/soc-dwt.ads
  src/arch/socs/stm32f439/soc-gpio-interfaces.ads
  src/arch/socs/stm32f439/soc-interrupts.ads
  src/ewok-debug.adb
  src/ewok-debug.ads
  src/ewok-interrupts-handler.adb
  src/ewok-rng-interfaces.ads
  src/ewok-softirq.ads
  src/ewok-tasks.ads
  src/syscalls/ewok-syscalls-init.ads
Labels: cleaning

#18 [update] Cleaning, fixing minor things...
  prove/prove.gpr
  src/arch/cores/armv7-m/m4-fpu.ads
  src/arch/socs/stm32f407/soc-pwr.ads
  src/arch/socs/stm32f439/soc-dwt.adb
  src/arch/socs/stm32f439/soc-flash.ads
  src/arch/socs/stm32f439/soc-pwr.ads
  src/arch/socs/stm32f439/soc-usart-interfaces.ads
Labels: cleaning

#21 [update] Removed useless code
  src/ewok-dma-interfaces.adb
  src/ewok-dma-interfaces.ads
  src/ewok-dma.adb
  src/ewok-init.adb
  src/ewok-isr.adb
  src/ewok-rng-interfaces.adb
  src/ewok-rng-interfaces.ads
  src/ewok-syscalls-handler.adb
  src/ewok-tasks.adb
  src/ewok-tasks.ads
  src/libgnat/gnat.gpr
  src/libkernel.gpr
  src/syscalls/ewok-syscalls-init.adb
Labels: cleaning

#22 [enhancement] Cleaning MPU management
  src/arch/cores/armv7-m/m4-mpu.adb
  src/arch/cores/armv7-m/m4-mpu.ads
  src/ewok-devices.adb
  src/ewok-mpu.adb
  src/ewok-mpu.ads
  src/ewok-sched.adb
  src/ewok-syscalls-handler.adb
  src/ewok-tasks.ads
Labels: enhancement
